# Generated by Django 5.2.5 on 2025-08-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Painkiller', 'Painkiller'), ('Vitamin', 'Vitamin'), ('Supplement', 'Supplement'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
