# Generated by Django 5.2.5 on 2025-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Personal Care', 'Personal Care'), ('OTC', 'Over the Counter'), ('Prescription', 'Prescription')], max_length=50),
        ),
    ]
