# Generated by Django 5.2.5 on 2025-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Vitamins', 'Vitamins'), ('Supplements', 'Supplements'), ('Personal Care', 'Personal Care'), ('Antibiotics', 'Antibiotics'), ('Painkiller', 'Painkiller')], max_length=50),
        ),
    ]
