# Generated by Django 5.0.6 on 2025-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Vitamins', 'Vitamins'), ('Supplements', 'Supplements'), ('Personal Care', 'Personal Care'), ('Antibiotics', 'Antibiotics'), ('Painkiller', 'Painkillers'), ('Prescription', 'Prescription'), ('Other', 'Other')], max_length=50),
        ),
    ]
